### PR TITLE
[wip] Sailfish improvements

### PR DESCRIPTION
**Pull request by piggz**

### CODE REVIEW

**Comment by janbar** [comment]
Nice. I am currently re-installing Sailfish on my xperia. I tested it 6 month ago. So re-back to Sailfish to see your improvements.

**Comment by janbar** [comment]
Can I merge now ?

**Comment by piggz** [comment]
How about merge now, this last commit fixes the music toolbar size.  Feel free to review if you think ive done anything against the design, im weary that im removing some specific sizings.

**Comment by piggz** [comment]
That last commit introduced a binding loop, even though it looks better, so i will revisit it.

**Comment by janbar** [comment]
Yo, Sailfish is installed on my phone and the app is working ;). I will help to improve the sizing of thing.

**Comment by janbar** [comment]
Currently to change the size of things, you need to update the grid value in Units

```property real gridUnit: 16.0 * scaleFactor```

I am testing with 24.0 ...

**Pull request merged**
