### PR TITLE
Use non-linear mapping to volume control

### PR DESCRIPTION
**Pull request by sandsmark**
Use a slightly non-linear mapping from shown volume to
controlled/reported volume. Just from testing it works better, but x^1.5
was chosen a bit arbitrarily based on some testing.

Ref; https://www.dr-lex.be/info-stuff/volumecontrols.html

Edit: found some theory and changed the constant to 1/0.67, ref https://en.wikipedia.org/wiki/Stevens%27s_power_law

### CODE REVIEW

**Comment by sandsmark** [comment]
Wasn't sure exactly where to fix this (could've done it in c++ or Player.qml), but I changed it where I thought it would have the least chance of impacting any other code.

**Comment by janbar** [comment]
I tried it and made a fix in branch [non_linear_volume](https://github.com/janbar/noson-app/tree/non_linear_volume).
As I know the volume control uses already a map based on sound pressure (db): The voltage value derives from log2. Adding +3db is factor sqrt(2) ~ 0.707.

**Comment by sandsmark** [comment]
FWIW, I just started empirically because the volume control was hard to adjust precisely, and the first value (x^1.5) was just something I arrived at by testing. Then I looked around a bit, and found that the voltage/loudness relationship seemed to match what I had ended up at.

Your branch looks a bit cleaner than mine, so if you want to merge that instead I can close this.

**Comment by janbar** [comment]
Hi Martin, I will merge this feature in the 3.11. I wish to add a setting to switch off/on. I could namel it "Smart volume".

**Comment by lin007pro** [comment]
Hi,

Maybe unrelated, but could you please add fixed volume detection?

Many thanks!
Michael

**Comment by janbar** [comment]
@lin007pro , thanks for the info. I didn't know about this setting. I will include the feature in the next release.

**Comment by lin007pro** [comment]
@janbar 
Thank you so, so much!!!

Michael

**Comment by sandsmark** [comment]
I tried adding a setting for it, but it wasn't as straightforward as I assumed... (mostly because of property propagation ordering in QML, how the qtquickcontrols2 Slider doesn't work as I want, etc.).

**Comment by sandsmark** [comment]
I was brazen enough to enable it by default (it might seem like an audiophile technical correctness thing, but at least in my living room it goes from having to hit the right pixel on the slider to get a sensible volume, to just clicking in about the right area).

**Comment by janbar** [comment]
I will try it soon and let you know about.

**Comment by janbar** [comment]
About "linear volume control": The volume control of the Sonos devices as every audio device is already logarithmic. The scale 0% ~ 100% is a position in the log scale. You could check it by moving for 5 units, then the sound pressure (decibels) grows in a linear manner : you hear the sound grow linearly, but the electrical power grow by +3db (x 1.414).
The feeling on low volume depends on the efficiency of the speakers you use. Here I use medium or high efficient speakers (91db, 93db and 99db depending of the room).
I will try the commit to know what happens ...

**Comment by janbar** [comment]
As I can understand, you need a fine grained volume control. Currently the volume slider has a minimal step of 2.5 units, and so you cannot select an intermediate position. The usage of the step was made to fix an historical issue to fix the race condition with the upnp feedback. Later I have refactored code for the control and a minimal step is no longer needed. My last commit set the step to 1 unit.

**Comment by janbar** [comment]
Hi, I reduced the volume step to the minimal: 1.0

**Comment by sandsmark** [comment]
Sorry for not responding earlier, but when I was poking at the API to implement the sub gain, I found out that there is actually a separate `SetVolumeDB` call.

So I think it currently is linear (i. e. voltage space or whatever), but I'll just close this since it is a rather ugly hack (though it felt nice here).

**Pull request closed without merging**
