### PR TITLE
[WIP] Sailfish port

### PR DESCRIPTION
**Pull request by piggz**
Hi, this is a WIP PR for info and feedback

This ports the application to Sailfish OS.  Because the sailfish Qt version is 5.6, I decided it was easier to copy the UI to a new folder, and make changes to all the Qml source, as there are no QQC2 available.

Some basic features are working, I can add a service, browse a service, select a zone, view a zone playlist.

Much to do, I havnt even added NowPlaying yet!

### CODE REVIEW

**Comment by piggz** [comment]
Port is coming on ok, I made a beta release here https://openrepos.net/content/piggz/noson-beta where you can see screenshots.

**Comment by janbar** [comment]
Hard work !
I can create a special branch for the sailfish devices. Maybe it could easier to merge small change...

**Comment by janbar** [comment]
The Silica design is really nice. I tried to compile your branch with the Sailfish SDK without success. I get an error at the cmake stage. I will retry later.

**Comment by piggz** [comment]
im not sure how to use qtcreator in the sdk to do the build, i use the sdk from the porters hadk chroot. you should be able to ssh into the build engine of the sdk and do the build there manually, it will be close to how i do it.  i also have a separate project on my github with the .spec file and git submodule for making the rpm.

**Comment by janbar** [comment]
I rebased your branch sailfish on the latest release (4.1.0). I will push my change soon. We are not so far ...

Capture du 2019-12-15 17-42-23

**Comment by janbar** [comment]
My fork of your branch is "build-sfos". I will fix some details to finalize the rebase, and I will make a PR for your branch.

**Comment by piggz** [comment]
Awesome, do you have a sfos device or are you running on the emulator?  I have a bunch of stuff push to my branch in a few minutes for more dialog fixes and page menus

**Comment by piggz** [comment]
I pushed some more changes.  This now uses a push up menu for the options menu.  There is a bug still in it because the mini player toolbar sits on top of it.  This can be fixed by moving the player into the flickable for the page.  What do you think?

**Comment by piggz** [comment]
Please try out the latest set of changes, its looking quite complete now i hope!

**Comment by janbar** [comment]
Hi, I fixed the few details including the issue with the mini player toolbar. So no need to copy it in all page instances. I use the emulator to test the app also I have an Xperia supporting Sailfish but it is running Android for instance ;-).
Still to merge your last changes, and I will make a PR for you.

**Comment by piggz** [comment]
great, ill hold off making more changes today as i imaging all these changes will get difficult to merge.  you really ought to fix the os on your xperia ;)

**Comment by piggz** [comment]
would it be better for me to rebase on the build-sfos branch?

**Comment by janbar** [comment]
Yes I think it will be faster. A rebase or a reset hard.

**Comment by piggz** [comment]
Btw, do you have telegram or some other way to discuss things?

**Comment by piggz** [comment]
Makes sense to close this PR and start from the new one?

**Comment by janbar** [comment]
Hi @piggz , why not. Once you think you have a first branch with goodies to release I will merge the PR into the master. You can create a new PR for WIP. And I could propose some PR to your branch until we merge.
I just added a commit to make working This device. All work great and we can play music file stored in the folder Music of nemo.

**Comment by janbar** [comment]
What else, you know better than me the look and feel of Sailfish, so feel free to adapt existing things. The target is to make a nice app for the Jolla devives.

**Comment by piggz** [comment]
Currently, on my phone, the sizing is a bit wrong, everything is smaller than on my first version.  I think the real fix, which will get rid of the pixel/point warnings, is to convert all the calls from pointSize to pixelSize

**Pull request closed without merging**
